# Generated by Django 5.2 on 2025-06-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='usertype',
            field=models.CharField(choices=[('landlord', 'Landlord'), ('rentseeker', 'Rentseeker')], max_length=100),
        ),
    ]
