# Generated by Django 5.2 on 2025-06-20 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='usertype',
            field=models.CharField(blank=True, choices=[('landlord', 'Landlord'), ('rentseeker', 'Rentseeker')], default='rentseeker', max_length=100, null=True),
        ),
    ]
