# Generated by Django 5.2 on 2025-06-07 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='RequestRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('phone', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=200)),
                ('property', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('area', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('phone', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254)),
                ('location1', models.CharField(max_length=200)),
                ('location2', models.CharField(max_length=200)),
                ('property1', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('area', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='property_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=60)),
                ('price', models.IntegerField()),
                ('extra_info', models.TextField()),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UI.choice1')),
            ],
        ),
    ]
