# Generated by Django 5.2 on 2025-06-04 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=60)),
                ('price', models.IntegerField()),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UI.choice1')),
            ],
        ),
    ]
