# Generated by Django 5.2 on 2025-06-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='request_room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=200)),
                ('property', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('area', models.CharField(max_length=100)),
            ],
        ),
    ]
