# Generated by Django 5.2 on 2025-06-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_post',
            name='photo1',
            field=models.ImageField(upload_to='property_images'),
        ),
        migrations.AlterField(
            model_name='property_post',
            name='photo2',
            field=models.ImageField(upload_to='property_images'),
        ),
        migrations.AlterField(
            model_name='property_post',
            name='photo3',
            field=models.ImageField(blank=True, upload_to='property_images'),
        ),
        migrations.AlterField(
            model_name='property_post',
            name='photo4',
            field=models.ImageField(blank=True, upload_to='property_images'),
        ),
        migrations.AlterField(
            model_name='property_post',
            name='video',
            field=models.FileField(upload_to='property_video'),
        ),
    ]
