# Generated by Django 5.2 on 2025-06-11 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shifthome',
            name='area',
        ),
        migrations.RemoveField(
            model_name='shifthome',
            name='fullname',
        ),
        migrations.AddField(
            model_name='property_post',
            name='booking_type',
            field=models.CharField(choices=[('instant', 'Instant Booking'), ('schedule', 'Schedule For Later')], default='instant', max_length=20),
        ),
        migrations.AddField(
            model_name='shifthome',
            name='bed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shifthome',
            name='cupboard',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shifthome',
            name='sofa',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shifthome',
            name='table',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shifthome',
            name='time',
            field=models.TimeField(default=datetime.datetime(2025, 6, 11, 13, 17, 9, 776276, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='shifthome',
            name='tv',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shifthome',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 6, 11, 13, 17, 9, 776276, tzinfo=datetime.timezone.utc)),
        ),
    ]
