# Generated by Django 5.2 on 2025-06-04 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0002_request_room'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='request_room',
            new_name='requestroom',
        ),
    ]
