# Generated by Django 5.2 on 2025-06-11 13:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0002_remove_shifthome_area_remove_shifthome_fullname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property_post',
            name='booking_type',
        ),
        migrations.AddField(
            model_name='shifthome',
            name='booking_type',
            field=models.CharField(choices=[('instant', 'Instant Booking'), ('schedule', 'Schedule For Later')], default='instant', max_length=20),
        ),
        migrations.AlterField(
            model_name='shifthome',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='shifthome',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
