# Generated by Django 5.2 on 2025-06-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0002_alter_property_post_photo1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='property_video'),
        ),
    ]
