# Generated by Django 5.2 on 2025-06-21 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0002_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fraud_Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_report', models.BooleanField(default=False)),
                ('property_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UI.property_post')),
            ],
        ),
    ]
