# Generated by Django 5.2 on 2025-06-04 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0003_rename_request_room_requestroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestroom',
            name='phone',
        ),
    ]
