# Generated by Django 5.2 on 2025-06-11 13:56

import UI.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0003_remove_property_post_booking_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifthome',
            name='date',
            field=models.DateField(default=UI.models.current_date),
        ),
        migrations.AlterField(
            model_name='shifthome',
            name='time',
            field=models.TimeField(default=UI.models.one_hour_later),
        ),
    ]
