# Generated by Django 5.2 on 2025-06-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0003_alter_property_post_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_post',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
