# Generated by Django 5.2 on 2025-06-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0004_remove_requestroom_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('location1', models.CharField(max_length=200)),
                ('location2', models.CharField(max_length=200)),
                ('property1', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('area', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
