# Generated by Django 5.2 on 2025-06-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0004_fraud_reports_reporter_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraud_reports',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
