# Generated by Django 5.2 on 2025-06-11 17:02

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0004_alter_shifthome_date_alter_shifthome_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifthome',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='NP'),
        ),
    ]
