# Generated by Django 5.2 on 2025-06-15 16:39

import UI.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0004_property_post_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_post',
            name='date',
            field=models.DateField(default=UI.models.current_date),
        ),
        migrations.AddField(
            model_name='property_post',
            name='time',
            field=models.TimeField(default=UI.models.one_hour_later),
        ),
    ]
