# Generated by Django 5.2 on 2025-06-07 08:37

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0005_shifthome'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestroom',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default=1, max_length=128, region='NP'),
        ),
        migrations.AddField(
            model_name='shifthome',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default=1, max_length=128, region='NP'),
        ),
    ]
