# Generated by Django 5.2 on 2025-06-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0005_fraud_reports_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_post',
            name='is_reports',
            field=models.BooleanField(default=False),
        ),
    ]
