# Generated by Django 5.2 on 2025-06-11 17:05

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0005_alter_shifthome_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestroom',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='NP'),
        ),
    ]
