# Generated by Django 5.2 on 2025-06-07 08:39

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0006_requestroom_phone_shifthome_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestroom',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='shifthome',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
