# Generated by Django 5.2 on 2025-06-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0008_inquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
