# Generated by Django 5.2 on 2025-06-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0010_testimonals'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonals',
            name='image',
            field=models.ImageField(null=True, upload_to='testimonals'),
        ),
        migrations.AddField(
            model_name='testimonals',
            name='user_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
