# Generated by Django 5.2 on 2025-07-01 11:51

import UI.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0011_testimonals_image_testimonals_user_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='comment_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date', models.DateField(default=UI.models.current_date)),
                ('time', models.TimeField(default=UI.models.one_hour_later)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UI.property_post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
